### ISSUE TITLE
Allow tables as statistics log sources

### ISSUE THREAD

**Issue by michaelcahill** [wiredtiger/wiredtiger#1207]
We currently only allow "file:" and "lsm:" URIs, which we find by walking the list of data handles.  We should support "table:" URIs, which we can do by:

1. making tables into real data sources;
2. using `__wt_schema_worker` to identify data sources instead of walking the list directly; or
3. writing special-case code in the statistics logger to walk tables.

**Comment by sueloverso** [comment]
@keithbostic Can this issue be closed?  Currently both `ex_stat.c` and `ex_all.c` have examples where we open and use a statistics cursor with a `table:name` URI.  So is this work already done?
