### ISSUE TITLE
Flush dirty pages without evicting them

### ISSUE THREAD

**Issue by agorrod** [wiredtiger/wiredtiger#1350]
It would be nice to be able to flush dirty pages from cache without evicting them. Some workloads don't generate a lot of cache pressure, but do want to do checkpoints.

If the cache is allowed to have a lot of dirty content then checkpoints become more expensive.

It would be good if ```eviction_dirty_target``` is set below ```evicting_target``` we switched to a mode of only "cleaning" dirty pages, rather than evicting them.

**Comment by keithbostic** [comment]
Alex, a question about this: isn't that what we do with the initial pass before each checkpoint to clear out dirty pages?

I guess this would keep checkpoints from taking so long, is that the goal?
