### ISSUE TITLE
Transaction error set on API_END

### ISSUE THREAD

**Issue by agorrod** [wiredtiger/wiredtiger#1395]
At the moment the ```API_END``` macro always sets ```TXN_ERROR``` for any error other than ```WT_NOTFOUND``` and ```WT_DUPLICATE_KEY```.

That is overly aggressive. For example a ```WT_CURSOR::open``` call that returns ```EBUSY``` should not mean that we need to abort/restart the transaction.

**Comment by keithbostic** [comment]
@michaelcahill, @agorrod: I took a look at this today, and I don't see any easy fix for this. It's not obvious to me that it's worth fixing, either (the example, opening a cursor inside a transaction, isn't a good idea, and the chances the open will fail are presumably low).

Is there a better example of why we need to make this change?

**Comment by agorrod** [comment]
> opening a cursor inside a transaction, isn't a good idea, and the chances the open will fail are presumably low

Why is it a bad idea to open a cursor while a transaction is open? I don't remember the exact use case but this was driven by code that was in the MongoDB integration layer. I was surprised that the transaction needed aborting, which is why I opened the issue.

**Comment by keithbostic** [comment]
I just meant to argue a cursor open is a long-running and heavy-weight operation, so opening a cursor inside a transaction means the transaction takes too long and is more likely to be aborted because something else interferes. I would say an unnecessary, long-running operation inside a transaction is bad program design, my first response would be to see if the cursor open can be done elsewhere (and the cursor cached).

**Comment by agorrod** [comment]
I think the behavior is worth fixing because it's not obvious to correlate the ```open_cursor``` error return with the transaction being aborted. I might write code like:

```
s->begin_transaction();
if (s->open_cursor("table:t1", &c) == ENOENT) {
    s->create("table:t");
    s->open_cursor("table:t1", &c);
}
c->set_key(key);
...

s->commit_transaction();
```

I can see that the above code is not great (I'd always recommend creating outside of a transaction scope), on the other hand I think it should work as written. Fundamentally it seems broken to me that an operation that isn't touching any data (open_cursor) can cause my transaction to be rolled back.

**Comment by keithbostic** [comment]
I won't fight more about this one -- but are you planning to guarantee `open_cursor` won't ever touch data?

The above code is just wrong -- anyone who has an operation inside a transaction that doesn't handle error and then abort is going to get burned.

**Comment by agorrod** [comment]
> I won't fight more about this one -- but are you planning to guarantee open_cursor won't ever touch data?

I think we should guarantee that ```open_cursor``` doesn't trigger a transaction abort unless it returns ```WT_ROLLBACK```. In fact I think most session methods should operate on that premise.
