### ISSUE TITLE
pkgconfig

### ISSUE THREAD

**Issue by amirouche** [wiredtiger/wiredtiger#1458]
Current .pc file has the following configuration 

```
Libs: -L${libdir} -lwiredtiger-@VERSION_NOPATCH@
Cflags: -I${includedir}/wiredtiger-@VERSION_NOPATCH@
```

but the shared library is named ```wiredtiger.so``` and there is no ```wiredtiger-@VERSION_NOPATCH@``` directory in ```${includedir}```

**Comment by ddanderson** [comment]
The pkg-config change was made/merged, and the Jenkins job `wiredtiger-configure-combinations` was modified to test it.  Closing.
