### ISSUE TITLE
the statistics of overflow key/value items is incorrect

### ISSUE THREAD

**Issue by keithbostic** [wiredtiger/wiredtiger#1520]
At some point the statistics of overflow key/values and the tree iteration code (the walk function) diverged; the statistics code thinks walk will return overflow pages and it no longer does.

Rewrite the statistics code to count overflow records as it processes internal/leaf pages.

Add tests in the test suite to confirm statistics returns the correct count of overflow key/value items correct.

**Comment by keithbostic** [comment]
I now remember why this was hard -- we explicitly removed the functionality that returned how many overflow items were in a particular object in March of 2011, commit 30a64f4.

We didn't remove the `btree: overflow pages` at the same time, which may have been a bug -- the tree-walk subroutine never returns overflow pages separately from the tree internal/leaf pages, so that statistic is never going to be non-zero in the current code base.

Staring at this a bit, I think we can enable users to figure out how many overflow chunks exist in the tree, but it's going to be a fair amount of complexity.

**Comment by keithbostic** [comment]
@michaelcahill: I'd like to talk this one over with you before proceeding further.

An idea that occurred to me last night is we could process the original disk chunks of the object rather than parse the in-memory structures (which would significantly reduce the complexity and maintenance of these kinds of object statistics going forward). Obviously, that implies object statistics are not associated with the **up-to-the-minute** in-memory cached object, but I can almost rationalize that as a feature, not a bug. We could even open a cursor on the last checkpoint, instead of trying to read the in-memory structures from the cache, and then statistics are as of the last checkpoint instead of a snapshot of the cache.

**Comment by agorrod** [comment]
> open a cursor on the last checkpoint, instead of trying to read the
in-memory structures from the cache, and then statistics are as of the last
checkpoint instead of a snapshot of the cache.

Do you mean all statistics or just the ones related to overflow items?

- Alex

**Comment by keithbostic** [comment]
I meant all underlying object statistics, the ones we read from the file.  (Which are pretty minimal actually, the count of pages, key/value pairs, overflow items, deleted items.)

**Comment by agorrod** [comment]
It is pretty easy to construct use cases where the checkpoint will be out of date enough that only gathering stats from the checkpoint is confusing for the user. Even just using the latest on-disk information worries me - what if a user configures a 64GB cache - the on-disk information could be quite misleading (e.g it will only reflect forced eviction for a very long time).

**Comment by keithbostic** [comment]
Closed with the merge of #1711.
