### ISSUE TITLE
Core dump when run the java example code ex_thread.java

### ISSUE THREAD

**Issue by flyaway921** [wiredtiger/wiredtiger#1524]
Hi friends @agorrod , I am going to integrate wiredtiger 2.4.1 into ycsb but meet some problem.
Before I report this issue, I passed the C example "ex_thread" both on 2.4.1 and 2.5.0, but when I run the jni example code I hit Core dump. Did any one hit the same error like this, If some one need the core file please paste your email.

Got record: key1 : value1
Got record: key1 : value1
Got record: key1 : value1
Got record: key1 : value1
Got record: key1 : value1
Got record: key1 : value1
Got record: key1 : value1
Got record: key1 : value1
Got record: key1 : value1
Got record: key1 : value1
\#
\# A fatal error has been detected by the Java Runtime Environment:
\#
\#  SIGSEGV (0xb) at pc=0x00007f5d53aafb8e, pid=29248, tid=140038805763840
\#
\# JRE version: Java(TM) SE Runtime Environment (7.0_67-b01) (build 1.7.0_67-b01)
\# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.65-b04 mixed mode linux-amd64 compressed oops)
\# Problematic frame:
\# V  [libjvm.so+0x653b8e]  jni_GetObjectClass+0x2e
\#
\# Core dump written. Default location: /schooner/backup/wcao/YCSB_ZS/wiredtiger/core or core.29248
\#
\# An error report file with more information is saved as:
\# /schooner/backup/wcao/YCSB_ZS/wiredtiger/hs_err_pid29248.log
\#
\# If you would like to submit a bug report, please visit:
\#   http://bugreport.sun.com/bugreport/crash.jsp
\# The crash happened outside the Java Virtual Machine in native code.
\# See problematic frame for where to report the bug.
\#

**Comment by ddanderson** [comment]
Hello @flyaway921, thanks for the bug report.
Can you try the fix in #1526 for this?  You can see the changes in  2d61ce5.

**Comment by flyaway921** [comment]
Hi @ddanderson  , I have tried your latest code and passed the test. Thanks for your help.
