### ISSUE TITLE
__wt_clsm_open calls __clsm_close

### ISSUE THREAD

**Issue by keithbostic** [wiredtiger/wiredtiger#1527]
@agorrod, I had a question about `__wt_clsm_open` I didn't want to lose, so I'm creating an issue.

Obviously, not urgent.

 In `__wt_clsm_open`, there's this code:
```
        /* 
         * The tree's dsk_gen starts at one, so starting the cursor on zero
         * will force a call into open_cursors on the first operation.
         */
        clsm->dsk_gen = 0;
         
        WT_STATIC_ASSERT(offsetof(WT_CURSOR_LSM, iface) == 0);
        WT_ERR(__wt_cursor_init(cursor, cursor->uri, owner, cfg, cursorp));
        
        if (0) {
err:            __wt_lsm_tree_release(session, lsm_tree);
                if (clsm != NULL) {
                        clsm->lsm_tree = NULL;
                        WT_TRET(__clsm_close(cursor));
                }
        }
```
This is probably wrong, I think we should be able to call `free(clsm)` instead of `__clsm_close`; if I'm wrong, we shouldn't call `__wt_lsm_tree_release`, as `__clsm_close` does that, and in this case I think the current code would result in `__wt_lsm_tree_release` being called twice.

**Comment by michaelcahill** [comment]
I haven't looked closely, but I don't see the problem -- we clear 'clsm->lsm_tree' before calling `__clsm_close`, so there's no chance of it being called twice.  I suspect the code ended up this way to make it unambiguous that we release the tree, even if allocating the cursor handle fails.

**Comment by keithbostic** [comment]
@michaelcahill, fair enough, sorry I missed that!

I was reacting mostly to the fact this is the only cursor-open routine that calls cursor-close instead of free in the error path -- if this is all good, it's fine with me.

**Comment by agorrod** [comment]
I'm with Michael here - I don't think we need to go through the close path, but I think it makes the code cleaner and less fragile.
