### ISSUE TITLE
illegal huffman config panics LSM

### ISSUE THREAD

**Issue by keithbostic** [wiredtiger/wiredtiger#1536]
The following script:
```
import wiredtiger, wttest

# Test configuration strings.
class test_XXX(wttest.WiredTigerTestCase):
    def test_XXX(self):
        self.session.create('table:foo', 'type=lsm,huffman_key=XXX')

if __name__ == '__main__':
    wttest.run()
```
panics WiredTiger:
```
f.test_XXX.test_XXX, file:foo-000001.lsm, session.create: unknown Huffman configuration value XXX: Invalid argument
f.test_XXX.test_XXX, session.create: Failed doing LSM switch: Invalid argument
f.test_XXX.test_XXX, session.create: the WiredTiger library cannot continue; the process must exit and restart
f.test_XXX.test_XXX, cursor.set_key: the WiredTiger library cannot continue; the process must exit and restart
f.test_XXX.test_XXX, file:WiredTiger.wt, cursor.search: the WiredTiger library cannot continue; the process must exit and restart
f.test_XXX.test_XXX, file:WiredTiger.wt, cursor.close: the WiredTiger library cannot continue; the process must exit and restart
f.test_XXX.test_XXX, session.create: metadata unroll remove: file:foo-000001.lsm: WT_PANIC: WiredTiger library panic
f.test_XXX.test_XXX, cursor.set_key: the WiredTiger library cannot continue; the process must exit and restart
f.test_XXX.test_XXX, file:WiredTiger.wt, cursor.search: the WiredTiger library cannot continue; the process must exit and restart
f.test_XXX.test_XXX, file:WiredTiger.wt, cursor.close: the WiredTiger library cannot continue; the process must exit and restart
f.test_XXX.test_XXX, session.create: metadata unroll remove: lsm:foo: WT_PANIC: WiredTiger library panic
f.test_XXX.test_XXX, cursor.set_key: the WiredTiger library cannot continue; the process must exit and restart
f.test_XXX.test_XXX, file:WiredTiger.wt, cursor.search: the WiredTiger library cannot continue; the process must exit and restart
f.test_XXX.test_XXX, file:WiredTiger.wt, cursor.close: the WiredTiger library cannot continue; the process must exit and restart
f.test_XXX.test_XXX, session.create: metadata unroll remove: table:foo: WT_PANIC: WiredTiger library panic
f.test_XXX.test_XXX, connection.close: the WiredTiger library cannot continue; the process must exit and restart
f.test_XXX.test_XXX, session.close: the WiredTiger library cannot continue; the process must exit and restart
f.test_XXX.test_XXX, session.close: the WiredTiger library cannot continue; the process must exit and restart
f.test_XXX.test_XXX, session.close: the WiredTiger library cannot continue; the process must exit and restart
f.test_XXX.test_XXX, session.close: the WiredTiger library cannot continue; the process must exit and restart
f.test_XXX.test_XXX, session.close: the WiredTiger library cannot continue; the process must exit and restart
f.test_XXX.test_XXX, session.close: the WiredTiger library cannot continue; the process must exit and restart
f.test_XXX.test_XXX, file:WiredTiger.wt, connection.close: pthread_rwlock_destroy: data handle: Resource busy
f.test_XXX.test_XXX, session.close: the WiredTiger library cannot continue; the process must exit and restart
f.test_XXX.test_XXX, session.close: the WiredTiger library cannot continue; the process must exit and restart
```

**Comment by sueloverso** [comment]
Looking at the docs and the code, we appear to be missing the checks on the configuration strings.  They're not specified as exact choices in api_data.py because the UTF ones are prefixes.  In `__wt_btree_huffman_open` where we parse the config, we need to check.  I'll add that.

**Comment by keithbostic** [comment]
This one still isn't quite right. If I run the test script, the incorrect Huffman configuration is ignored, note the `huffman_key=XXX` configuration in the file.
```
% wt dump file:WiredTiger.wt
WiredTiger Dump (WiredTiger Version 2.5.1)
Format=print
Header
metadata:
allocation_size=4KB,app_metadata=,block_allocation=best,block_compressor=,
cache_resident=0,checksum=uncompressed,colgroups=,collator=,columns=,
dictionary=0,exclusive=0,extractor=,format=btree,huffman_key=,huffman_value=,
immutable=0,internal_item_max=0,internal_key_max=0,internal_key_truncate=,
internal_page_max=4KB,key_format=S,key_gap=10,leaf_item_max=0,
leaf_key_max=0,leaf_page_max=32KB,leaf_value_max=0,lsm=
(auto_throttle=,bloom=,bloom_bit_count=16,bloom_config=,
bloom_hash_count=8,bloom_oldest=0,chunk_max=5GB,chunk_size=10MB,
merge_max=15,merge_min=0),memory_page_max=5MB,
os_cache_dirty_max=0,os_cache_max=0,prefix_compression=0,
prefix_compression_min=4,source=,split_pct=75,type=file,
value_format=S
Data
colgroup:foo\00
app_metadata=,columns=,source="lsm:foo",type=lsm\00
lsm:foo\00
key_format=u,value_format=u,bloom_config=(),file_config=(
type=lsm,huffman_key=XXX,key_format=u,value_format=u,key_format=u,
value_format=u,memory_page_max=10737418240),collator=,last=0,
chunk_max=5368709120,chunk_size=10485760,auto_throttle=1,merge_max=15,
merge_min=0,bloom=1,bloom_bit_count=16,bloom_hash_count=8,
chunks=[],old_chunks=[]\00
table:foo\00
app_metadata=,colgroups=,columns=,key_format=u,value_format=u\00
```

**Comment by sueloverso** [comment]
My changes appear to fix only the btree case.  When LSM is in use, the huffman config code is never actually called on `session->create` at all.  The LSM code just pastes the config into the metadata file without ever checking it, beyond the LSM-specific settings.

Although it doesn't seem to be related, #1534 is also a failure when huffman is on, with LSM.  In that case it is a valid huffman setting.

**Comment by michaelcahill** [comment]
In #1540, @sueloverso wrote:

> One outstanding issue is I found in my test that I could not use hex in the frequency file as shown in the docs. SCNu64 does not read hex. You'll notice test_huffman01.py writes decimal. We can fix the documentation or assume the values are hex, fix the code and document that requirement.
http://source.wiredtiger.com/2.5.0/huffman.html

**Comment by keithbostic** [comment]
Closed with the merge of #1540.

**Comment by sueloverso** [comment]
@keithbostic I don't think this is fixed for LSM.  I believe we still just write the config into the metadata file in that case and an invalid huffman config will be propogated.

**Comment by keithbostic** [comment]
@michaelcahill, @agorrod, @sueloverso:

I think the only way we can fix this one is to create an underlying file as part of creating the LSM tree.

A simple example is `huffman_key=utf64`: we won't validate `utf64` until we attempt to open a file based on that value.

Would it be reasonable to immediately open a file when we create an LSM object?

**Comment by agorrod** [comment]
It would be possible to create a file when creating an LSM tree - it feels pretty horrible to me though, and has namespace and performance consequences.

Could we consider splitting out configuration validation from the various open methods? That could help with #1739 as well.

I like it because it makes it simpler to define conditions on configuration settings. The downside is that I suspect we'll need to do additional configuration parsing on open - since I suspect there are places where we share parsing between setting and validating configurations. That's a price I'd be prepared to pay.

**Comment by keithbostic** [comment]
Doing configuration validation separately from the various open methods would be a relatively large undertaking, but it's fine with me, if we want to sign up for it. (I suspect we'd going to have to create per-API routines to validate all of the configuration values -- as you suggested, we'll end up doing more configuration parsing on open.)

**Comment by keithbostic** [comment]
@sueloverso, I'm closing #1536 again, I think with the merge of #1755, we've done everything we're going to do for now.

**Comment by sueloverso** [comment]
I pushed a test suite change that I've had sitting around for a while that now passes.  Yes, this is now fully resolved and closed.
