### ISSUE TITLE
Add cursor equality function

### ISSUE THREAD

**Issue by agorrod** [wiredtiger/wiredtiger#1538]
There are use cases where a lot of cursor comparisons are made, for example when using cursors like STL iterators, eg:

* Set cursor c2 to a location via a search (or the end via prev).
* Start a walk with cursor c1
* Each step forward with c1 compare to the position of c2 to see whether you have walked as far as you want.

In the above use case all we need is a simple equality check rather than a memcmp type comparison.

Additional information:
> the only thing we care about is whether two cursors point to the exact same place, how hard would it be to provide a faster "equals" operation on WT cursors? Ideally it wouldn't need to actually look at the data and could just look at the positioning information.

**Comment by keithbostic** [comment]
I didn't realize there was an open issue when I pushed #1541; the #1541 branch has cursor equality support.

**Comment by keithbostic** [comment]
Closed with the merge of #1541.
