### ISSUE TITLE
backup log URIs need to use log path

### ISSUE THREAD

**Issue by sueloverso** [wiredtiger/wiredtiger#1559]
It looks like `wt backup` with log files in a different path is not working.  References SERVER-16833.

**Comment by sueloverso** [comment]
@michaelcahill I've been thinking about this and this fix will set a precedent going forward so we should discuss it and decide what WT is responsible for, versus the caller.  The log path is the first non-database home files returned by a `backup:` cursor.  Currently for log files, the `backup:` cursor is returning only the log file name portion.

This issue would benefit from `config:` cursors (issue #1133).  Let's walk through what backup would need to do with no log path, a relative log path and an absolute log path on the source database and considerations on the destination side.

1.  No src log path.  Log files reside in database home.  backup cursor returns names like WiredTigerLog*.  Backup program copiees from <src home>/filename to <dest home>/filename.  This currently works.

2.  Relative src log path.   Log files reside in <home>/<logdir>.  Backup cursor currently returns names like WiredTigerLog*.  Currently this is broken because `wt backup` tries to copy from the <src home>/filename and gets ENOENT.  Possible avenues of fixing:
- Add args to `wt backup` to specify the src and dest logdir.  Would allow  `wt backup` to generate strings like <src home>/<src logdir>/<filename> and <dest home>/<dest logdir>/<filename> and, in fact, `mkdir <dest home>/<dest logdir>`.  That is a lot of args for the user to keep straight.  Maximum flexibility for the user.  Backup cursor continues to return only the log file name.
- Have the backup cursor prepend the log path, such as `logdir/WiredTigerLog*`.  The `wt backup` code then can use the current code.  First downside is that `wt backup` currently assumes all directories were created prior to calling, so the user would have to `mkdir <dest>/logdir` ahead of time.  Second downside is that this restricts the user to maintain the same relative naming of the log path in the backup.  That restriction is probably acceptable in the typical case.
- If/when we have `config:` cursors, `wt backup` could get the `log_path` setting and include that in the path.  The backup cursor would continue to return only the log file name.   Again either we assume the same directory structure on the destination side or add an arg to specify the log path in the destination.

3. Absolute src log path.  Log files reside in `/<dir>/<logdir>`.  Backup cursor currently returns only the file name portion.  Again this is currently broken because `wt backup` assumes all file names returned are relative to the database home.  Possible fixes include:
- Add args to `wt backup` to specify the src and dest logdir.  Would allow  `wt backup` to generate strings like /<src logdir>/<filename> and /<dest logdir>/<filename> if the given paths are absolute. That is a lot of args for the user to keep straight.  Maximum flexibility for the user.  Backup cursor continues to return only the log file name.
- Have the backup cursor prepend the log path such as `/tmp/logdir/WiredTigerLog*`.  This requires fixes/changes to `wt backup` to detect an absolute pathname in a name returned from the backup cursor.  Requires an additional arg to `wt backup` to indicate where the destination log path should be located.  Therefore this is no better than the first option.
- If/when we have `config:` cursors, `wt backup` could get the `log_path` setting and include that in the path.  The backup cursor would continue to return only the log file name.   Again we have to add an arg to specify the log path in the destination.

The absolute pathname case really drives things toward adding args to `wt` and having the backup cursor continue to return only the filename portion, therefore putting the responsibility on and giving maximum flexibility to the caller.

Other suggestions?

**Comment by michaelcahill** [comment]
Hi @sueloverso, one problem with any of the proposed solutions is that there is no way for the application to know whether a particular file belongs with the logs.  We could document that we call log files `WiredTigerLog*`, but that's potentially limiting in the future.

Could we add value columns to backup cursors with more information, including a source directory and a flag indicating the file type?

**Comment by sueloverso** [comment]
This also should ref #999
