### ISSUE TITLE
log-append workload, bad file descriptor

### ISSUE THREAD

**Issue by michaelcahill** [wiredtiger/wiredtiger#1571]
http://build.wiredtiger.com:8080/job/wiredtiger-perf-log-append/119/console

```
+ ../../../bench/wtperf/runners/wtperf_run.sh ../../../bench/wtperf/runners/log-append.wtperf 1
[1421440989:689126][21061:0x7f23987ff700]: (null) write error: failed to write 1536 bytes at offset 1042048: Bad file descriptor
```

**Comment by sueloverso** [comment]
There is no core file.  I've kicked this off on the AWS HD box to try to reproduce.

**Comment by sueloverso** [comment]
While in the thinking place I figured out how this happened.  I need to ponder the best way to fix it tonight.
