### ISSUE TITLE
Updated usage instructions for wtstats

### ISSUE THREAD

**Issue by agorrod** [wiredtiger/wiredtiger#1573]
The new version of wtstats requires building a template file using NPM, and then running a s_wtstats script from dist.

The error message when the template file isn't built has outdated instructions. The instructions should be updated to mention s_wtstats.

**Comment by agorrod** [comment]
@ddanderson @rueckstiess Could one of you please take a look at this? Both Darren and I were stumped by it for a while yesterday.

**Comment by keithbostic** [comment]
Close: we have committed a version of the wtstats template file into the develop branch, so a template file should always be available.
