### ISSUE TITLE
assertion failure for potential deadlock

### ISSUE THREAD

**Issue by sueloverso** [wiredtiger/wiredtiger#1589]
The `WT_WITH_TABLE_LOCK` assertion failed in https://jira.mongodb.org/browse/SERVER-16967.  This implies a potential deadlock situation.  The stack is:
```
wiredtiger\src\support\err.c(451)                 __wt_assert+0x37
wiredtiger\src\schema\schema_list.c(28)           __schema_add_table+0x6c
wiredtiger\src\schema\schema_list.c(99)           __wt_schema_get_table+0x64
wiredtiger\src\schema\schema_worker.c(83)         __wt_schema_worker+0x2ee
wiredtiger\src\txn\txn_ckpt.c(132)                __checkpoint_apply_all+0x1d1
wiredtiger\src\txn\txn_ckpt.c(346)                __wt_txn_checkpoint+0x1ca
wiredtiger\src\session\session_api.c(889)         __session_checkpoint+0x1b3
wiredtiger\src\session\session_compact.c(185)     __compact_file+0x101
wiredtiger\src\session\session_compact.c(235)     __wt_session_compact+0x250
```
The `WT_WITH_TABLE_LOCK` macro asserts that we do not hold the `dhandle_lock` and we do.  In this stack we acquire the `dhandle_lock` up in `__wt_txn_checkpoint` in this code:
```
        /*
         * Get a list of handles we want to flush; this may pull closed objects
         * into the session cache, but we're going to do that eventually anyway.
         */
        WT_WITH_SCHEMA_LOCK(session,
            WT_WITH_DHANDLE_LOCK(session,
                ret = __checkpoint_apply_all(
                session, cfg, __wt_checkpoint_list, NULL)));
```
In looking at the locking hierarchy, it appears, based on the WT_WITH_*_LOCK macros, that the schema lock is the highest level.  It asserts it does not hold either the table lock or the dhandle lock.  The table lock is 2nd as its macro asserts that it does not hold the dhandle lock.  Then the dhandle lock is last and it does not assert anything about lock state.

**Comment by sueloverso** [comment]
One code path to a deadlock would be that `__schema_add_table` takes the table lock and calls `__wt_schema_open_table`.  That calls `__wt_metadata_cursor` which can call down eventually into `__wt_session_get_btree` which acquires the dhandle lock.

**Comment by agorrod** [comment]
We used to cache the metadata handle separately in sessions. I wonder if we
should always open the metadata handle when opening a session?

**Comment by agorrod** [comment]
I can reproduce this one using test/fops. The secret is to call checkpoint with a table: uri, rather than just checkpointing at the file level.

I made the following changes to test/fops:

```
--- a/test/fops/file.c
+++ b/test/fops/file.c
@@ -184,12 +184,14 @@ obj_checkpoint(void)
 {
        WT_SESSION *session;
        int ret;
+       char config_str[512];
 
        if ((ret = conn->open_session(conn, NULL, NULL, &session)) != 0)
                die(ret, "conn.session");
 
        /* Force the checkpoint so it has to be taken. */
-       if ((ret = session->checkpoint(session, "force")) != 0)
+       snprintf(config_str, 512, "force,target=[\"%s\"]", uri);
+       if ((ret = session->checkpoint(session, config_str)) != 0)
                if (ret != ENOENT)
                        die(ret, "session.checkpoint");
 
diff --git a/test/fops/t.c b/test/fops/t.c
index 1522b59..c81cf91 100644
--- a/test/fops/t.c
+++ b/test/fops/t.c
@@ -57,12 +57,16 @@ main(int argc, char *argv[])
                const char *desc;
                const char *config;
        } *cp, configs[] = {
+#if 0
                { "file:wt",    NULL, NULL },
+#endif
                { "table:wt",   NULL, NULL },
 /* Configure for a modest cache size. */
 #define        LSM_CONFIG      "lsm=(chunk_size=1m,merge_max=2),leaf_page_max=4
+#if 0
                { "lsm:wt",     NULL, LSM_CONFIG },
                { "table:wt",   " [lsm]", "type=lsm," LSM_CONFIG },
+#endif
                { NULL,         NULL, NULL }
        };
        u_int nthreads;
```

Then run with:
```
$ ./test/fops/t -n 100000
t: process 21032
    1: 10 threads on table:wt
[1421965230:642345][21032:0x105912000], t, session.checkpoint: ../src/schema/schema_list.c, 28: F_ISSET(session, WT_SESSION_TABLE_LOCKED) || !F_ISSET(session, WT_SESSION_HANDLE_LIST_LOCKED)
[1421965230:642371][21032:0x105912000], t, session.checkpoint: aborting WiredTiger library
Abort trap: 6
```

Should make this one easier to track down.

In terms of the locks in the system, we have:

The schema lock (```WT_WITH_SCHEMA_LOCK```) that protects schema level operations, but doesn't block checkpoints.

The dhandle list lock (```WT_WITH_DHANDLE_LOCK```) that protects the list of dhandles in the connection structure.

The table list lock (```WT_WITH_TABLE_LOCK```) that protects the list of tables in the connection structure.

I'm surprised that the checkpoint is opening a table handle. Maybe what should happen is that checkpoints explicitly open any table handles they need prior to taking the schema lock?

**Comment by sueloverso** [comment]
> The table list lock (WT_WITH_TABLE_LOCK) that protects the list of tables in the connection structure.

There is no table list in the connection.  There is one in the session structure.  But uses of the session's table list are not protected.  That is clear in `schema_list.c:schema_add_table` where we do not lock during the `SLIST_INSERT_HEAD` call.

As best I can tell as I've studied more code this evening, I think the table lock is almost like a transaction for namespace operations that affect 1 or more files.  There may be column groups or indexes to create when creating a table, or dropping or rename.  It would be bad if say two renames to the same URI raced and we ended up with half of each instead of one succeeding and the other getting ENOENT.

I'm still no closer to figuring out where to break the deadlock in the code though, as different layers call each other and take/release those locks.

**Comment by agorrod** [comment]
> I'm still no closer to figuring out where to break the deadlock in the code though, as different layers call each other and take/release those locks.

Looking at the code in ```__checkpoint_apply_all``` I think we need to split it into two functions:

One that traverses the list of targets without the dhandle lock - building up a set of file handles. There are probably error paths out of this code if some of the targets don't exist that might be new. We may also need to take the dhandle lock if a target is a file: URI type.

Another that traverses the set of file handles while holding the dhandle lock - either those handles built up from a list of targets or the set gathered in ```__checkpoint_apply_all::__wt_conn_btree_apply``` at the moment.

So basically pulling:

```
	/* Step through the targets and optionally operate on each one. */
	WT_ERR(__wt_config_gets(session, cfg, "target", &cval));
	WT_ERR(__wt_config_subinit(session, &targetconf, &cval));
	while ((ret = __wt_config_next(&targetconf, &k, &v)) == 0) {
		if (!target_list) {
			WT_ERR(__wt_scr_alloc(session, 512, &tmp));
			target_list = 1;
		}

		if (v.len != 0)
			WT_ERR_MSG(session, EINVAL,
			    "invalid checkpoint target %.*s: URIs may require "
			    "quoting",
			    (int)cval.len, (char *)cval.str);

		/* Some objects don't support named checkpoints. */
		if (named)
			WT_ERR(__checkpoint_name_check(session, k.str));

		if (op == NULL)
			continue;
		WT_ERR(__wt_buf_fmt(session, tmp, "%.*s", (int)k.len, k.str));
		if ((ret = __wt_schema_worker(
		    session, tmp->data, op, NULL, cfg, 0)) != 0)
			WT_ERR_MSG(session, ret, "%s", (const char *)tmp->data);
	}
	WT_ERR_NOTFOUND_OK(ret);
```

Out into a separate function. The division is almost already there in ```__wt_txn_checkpoint```, which calls ```__checkpoint_apply_all``` twice.

**Comment by sueloverso** [comment]
This is fixed with the pull request, but should be retested with this change to force a checkpoint target when #1598 is completed.
