### ISSUE TITLE
Process for managing changes to statistics

### ISSUE THREAD

**Issue by michaelcahill** [wiredtiger/wiredtiger#1609]
We have had several requests to manage / minimize changes to statistics between releases of WiredTiger.  There are applications and tools that rely on either the prefixes or the complete description strings to monitor the behavior of workloads.

Given this, we should clarify how statistics may change between releases, and how WiredTiger users can track what has changed.

**Comment by keithbostic** [comment]
@michaelcahill, can we talk about this one?

I noticed today that some of our statistics:
```
ConnStat('cond_wait', 'pthread mutex condition wait calls'),
ConnStat('rwlock_read', 'pthread mutex shared lock read-lock calls'),
ConnStat('rwlock_write', 'pthread mutex shared lock write-lock calls'),
```
talk about `pthreads`, and that's simply wrong -- I'd like to fix it, but that's not backward compatible.
