### ISSUE TITLE
Verify that tracked page footprint matches actual footprint

### ISSUE THREAD

**Issue by agorrod** [wiredtiger/wiredtiger#1614]
WiredTiger has a class of bugs that amount to the tracking of cache usage (dirty and clean) getting out of sync with reality.

We track memory footprint on each individual page. We should also be able to calculate how much footprint we expect a page to have. It would be useful to have diagnostic code to validate that the field matches reality.

**Comment by agorrod** [comment]
@keithbostic I've started working on a change to implement this validation. I'm borrowing quite a lot of the code in bt_debug.c to walk through different parts of the page. I'm pinging you in case this is on your todo list as well, I'd rather not duplicate the work.

**Comment by keithbostic** [comment]
@agorrod, I've got some code, but nothing worth throwing over the fence -- go for it!

**Comment by bdlucas1** [comment]
Could I suggest also some unit tests that run various workloads and then
compare the accumulated usage stats with reality.

**Comment by keithbostic** [comment]
@bdlucas1, the idea is that (at least in diagnostic mode), we'll always be verifying the memory footprint against the accumulated values, so, for example, as part of discarding a page is confirming the calculated memory footprint of the page is the same as the current memory footprint.
