### ISSUE TITLE
__ovfl_txnc_wrapup race with transaction visible check

### ISSUE THREAD

**Issue by agorrod** [wiredtiger/wiredtiger#1615]
I believe there is a bug in __ovfl_txnc_wrapup. The current code removes entries from a skip list if they are old enough to no longer be required by an active transaction.

If the visible transaction moves forward in between the first pass that removes entries from the skip list above the bottom, and the second pass we could end up with pointers in the skip list that point to NULLs.

**Comment by keithbostic** [comment]
Close with the merge of #1616.
