### ISSUE TITLE
Reconciliation not filling leaf pages

### ISSUE THREAD

**Issue by agorrod** [wiredtiger/wiredtiger#1630]
Some workloads aren't filling leaf pages as expected. I have a workload that inserts 225 byte values and 25 byte keys. It inserts 3 million records, and has a 4KB page size. At the end of a run table statistics show that there are 427 thousand pages.

Calculating out how many pages there should be:

250 * 3 million = 750 million bytes
183,105 pages. With a split_pct of 75, that would translate into 228,881 pages - adding on a factor for overhead we should end up in the vicinity of 250k pages.

The change to fix #1282 (specifically 5088ee53f) introduced a change in the number of leaf pages generated in the workload from ~264k to ~427k pages.

**Comment by keithbostic** [comment]
@agorrod, are we done with #1630, are we filling leaf pages as efficiently in the workload?
