### ISSUE TITLE
Opening a cursor with many tables is slow

### ISSUE THREAD

**Issue by sueloverso** [wiredtiger/wiredtiger#1634]
This references https://jira.mongodb.org/browse/SERVER-17078.  Similar to the earlier issue, things get much slower as there are more tables to open.  I (again) modified `ex_stat` to create many tables and then open a stat cursor on each one.  On my Mac it takes 17 seconds to open/get a stat/close with a stat cursor on 10000 tables.  As the Jira issue point out, it appears that the three loops in `__wt_open` (twice walking the fh list) and `__wt_block_open` eat a lot of time.

I added name hashes for both of those structures to avoid the strcmp and that cuts it down to 15.5 seconds.  Zoom shows us spending, overall, 12.3 seconds in `__wt_curstat_open` of which 2.8 seconds (23%) is `__wt_block_open` (1.5 seconds) and `__wt_open` (1.3 seconds) and I've confirmed the line numbers are the hash comparison.  (Another 2.1 seconds (17%) is spent in `config_next`.)

Running with a statistics logging on and adding a stat counter in those loops shows that for 17084 curstat open calls, we were in the block name loop, and both open loops 36 million times each or an average of 2200 iterations through each loop for every curstat open call.  It looks like both of those structures may need the hash buckets like dhandles.

**Comment by sueloverso** [comment]
refs pull request #1635

**Comment by sueloverso** [comment]
I reran the original listDatabases test 3 times each from 17078 on 5000 collections (15000 files with 2 indexes per collection).
Current develop (in seconds): 16.9, 17.6, 18.5
Name-hash branch: 13.1, 9.4, 9.4

So the hashing has a marked effect.

**Comment by sueloverso** [comment]
The next item that is consuming a lot of time in this run (and my simulation of it with ex_stat) is `config.c:359:__config_next`.  In my zoom profile, I spend 12.6 seconds in `__wt_open_cursor` of which 3.5 seconds is spent in `__btree_conf`. 

Changing to a per-line leaf view in zoom, in this run, 2.9 seconds total is spent at `config.c:359` itself which is by far the most at any single line.  Second is `config.c:457` at 316 ms and third is `config.c:358` at 209 ms.  All three of those lines are part of the same loop in `__config_next`.

This workload is open-intensive and open is often heavyweight, but it clearly represents a common operation in MongoDB via listDatabases.

The config code is generally a black-box to me.  Anyone have suggestions on how we can improve its performance?  Can we parse it once and keep an array of cval's somewhere?

**Comment by sueloverso** [comment]
So, the `listDatabases` command, aka, `> show databases` ends up with this stack:
```
mongo::CmdListDatabases::run	mongod.exe	21,841	0	94.07	0.00
mongo::KVDatabaseCatalogEntry::sizeOnDisk	mongod.exe	21,841	7	94.07	0.03
mongo::WiredTigerKVEngine::getIdentSize	mongod.exe	11,318	1	48.75	0.00
mongo::WiredTigerUtil::getIdentSize	mongod.exe	11,306	3	48.69	0.01
mongo::WiredTigerUtil::getStatisticsValueAs<__int64>	mongod.exe	11,290	1	48.63	0.00
```
The statistics value they're getting is `WT_STAT_DSRC_BLOCK_SIZE`, which is essentially a `stat(2).st_size` for each file.  The metadata does not retain any information about the file size.

**Comment by sueloverso** [comment]
> Current develop (in seconds): 16.9, 17.6, 18.5
> Name-hash branch: 13.1, 9.4, 9.4

I should note that mmapv1 takes 0.001 (1 msec) to run this.

**Comment by keithbostic** [comment]
@sueloverso, it occurs to me the metadata does have information about the file size: it has a checkpoint size, which (depending on checkpoint frequency), isn't going to be that different. How accurate do we need to be?

Alternatively, we could have the block-manager return statistics about a file name, instead of an open file handle, if that would help?

**Comment by sueloverso** [comment]
@keithbostic I think this is an interesting avenue to pursue.  I do believe that "in the ballpark" is accurate enough.  I'll confirm that once we have a workable solution.  I believe the current practice of showing the size with a `listDatabases` call is because under mmapv1 it is very fast and easy information to include.  What you're suggesting is a lot like `wt list -c URI`.

Currently they open a statistics cursor on every table URI and get `WT_STAT_DSRC_BLOCK_SIZE`.  The large number of open calls are the issue, not really the stat call.  There would need to be a new or different code path up in the MongoDB layer, I think, to open a metadata cursor instead.  Or some other form of an API.  Looking at what the metadata contains, there is a bit of a translation needed too.  The URIs of `table:whatever` contain little information in the metadata.  The checkpoint information is stored in the metadata in the `file:whatever` portion.  So the calling code would have to translate their URI from `table` to `file` which seems ugly and fragile.

But I'd like to brainstorm a path here because I do think it can fix the issues with both large numbers of collections and databases and make things fast.

**Comment by sueloverso** [comment]
Last night on the call @michaelcahill suggested a statistics config setting, like `size-only`.  We agreed that this needs to be in the WT layer not the MongoDB integration layer.  
I've been thinking about this since then and one possibility might be a data-source only statistics cursor setting of `internal-only` or `fast-estimates` or something like that.  It would be a subset of the `fast` statistics.  Basically, a cursor of that type would not open(2) the underlying data source by default on `open_cursor`.

We would have a list of what data source statistics we have available internally without opening the file, all others would be zero (similar to `fast` versus `all`).  This might include things in memory or a walk through the metadata which could give us the size estimate based on checkpoint size.  I think most of the LSM DSRC statistics could be obtained from metadata and half or a bit more of the block manager DSRC statistics. 

Unfortunately, I don't think the current cursor open code for statistics cursors with a URI are structured in a way to easily skip the open of underlying files.

**Comment by keithbostic** [comment]
If there's no pressure from MongoDB to make this faster than it is now, I think we should leave this alone until there's pressure to work it further. (I'd also like to hear from somebody why this is useful: it may simply be file size is provided because it was easy to provide with mmapv1 and there aren't good end-user reasons to push this rock up the hill.)

I don't hate `size-only`, I don't like it a lot, but I could live with it.

I don't want to fragment `fast/all` any further, that's making a not-so-great solution worse, and there isn't much information we can provide without opening the handle.

**Comment by sueloverso** [comment]
I have updated the original ticket to ask if displaying the size could be removed.  We'll see what they say.

**Comment by sueloverso** [comment]
If I remove the loop in `commands/list_databases.cpp` that calls `sizeOnDisk` the time for 5000 collections and indexes for `show databases` goes from 12 seconds to about 60 msecs using `time`, which is fairly coarse.

**Comment by monkey101** [comment]
i'm kind of leaning to deprecating this functionality with WT.  Will move discussion to the SERVER ticket.
