### ISSUE TITLE
update list exceedingly long

### ISSUE THREAD

**Issue by sueloverso** [wiredtiger/wiredtiger#1647]
This references https://jira.mongodb.org/browse/SERVER-17195.  When there is highly contended update traffic to the same data, WT quickly appears to get stuck and throughput drops to nearly nothing.
```
insert query update delete getmore command % dirty % used flushes  vsize   res qr|qw ar|aw netIn netOut conn     time
    *0    *0  15963     *0       0     1|0     0.0    0.0       0 347.0M 80.0M   0|0  0|18    2m     1m   22 20:11:19
    *0    *0  15977     *0       0     1|0     0.0    0.0       0 348.0M 82.0M   0|0  0|15    2m     1m   22 20:11:20
    *0    *0  15915     *0       0     1|0     0.0    0.0       0 349.0M 83.0M   0|0  0|18    2m     1m   22 20:11:21
    *0    *0  15631     *0       0     1|0     0.0    0.0       1 350.0M 83.0M   0|0  0|12    2m     1m   22 20:11:29
    *0    *0  16095     *0       0     3|0     0.0    0.0       0 351.0M 84.0M   0|0  0|19    2m     1m   23 20:11:30
    *0    *0  16041     *0       0     1|0     0.0    0.0       0 352.0M 86.0M   0|0  0|18    2m     1m   23 20:11:31
    *0    *0   3411     *0       0     1|0     0.0    0.0       0 353.0M 86.0M   0|0  0|20  508k   258k   23 20:11:32
    *0    *0      2     *0       0     1|0     0.0    0.0       0 353.0M 86.0M   0|0  0|20  377b    16k   23 20:11:33
    *0    *0     *0     *0       0     2|0     0.0    0.0       0 353.0M 86.0M   0|0  0|20  133b    16k   23 20:11:34
    *0    *0      1     *0       0     1|0     0.0    0.0       0 353.0M 86.0M   0|0  0|20  228b    16k   23 20:11:35
```
When I run pmp on mongod during the (long) stuck time I always see everyone sleeping in `wt_page_in_func` and one thread in either `__rec_txn_read` or `__wt_update_list_memsize`.  Basically the update list is getting very long and it is taking a huge amount of time to walk it.  I added stats to `rec_txn_read` and while we see this issue happening, in the 5 second stat span, `__rec_txn_read` is called 635 times but we take almost 136M iterations through the update list loop, or an average of 200K iterations per call.

**Comment by sueloverso** [comment]
The range of txn ids is pretty small.  The test is using 20 threads.  Here is the range (when mongod was started and just sitting idle before the test started, the range was always 7, FYI):
```
Feb 06 20:11:14 66 /mnt/fast/sue/work/mongo/data/db transaction: transaction range of IDs currently pinned
Feb 06 20:11:19 48 /mnt/fast/sue/work/mongo/data/db transaction: transaction range of IDs currently pinned
Feb 06 20:11:29 134 /mnt/fast/sue/work/mongo/data/db transaction: transaction range of IDs currently pinned
Feb 06 20:11:34 3 /mnt/fast/sue/work/mongo/data/db transaction: transaction range of IDs currently pinned
Feb 06 20:11:39 6 /mnt/fast/sue/work/mongo/data/db transaction: transaction range of IDs currently pinned
Feb 06 20:11:44 4 /mnt/fast/sue/work/mongo/data/db transaction: transaction range of IDs currently pinned
Feb 06 20:11:53 6 /mnt/fast/sue/work/mongo/data/db transaction: transaction range of IDs currently pinned
Feb 06 20:11:58 16 /mnt/fast/sue/work/mongo/data/db transaction: transaction range of IDs currently pinned
Feb 06 20:12:03 19 /mnt/fast/sue/work/mongo/data/db transaction: transaction range of IDs currently pinned
Feb 06 20:12:08 15 /mnt/fast/sue/work/mongo/data/db transaction: transaction range of IDs currently pinned
Feb 06 20:12:17 5 /mnt/fast/sue/work/mongo/data/db transaction: transaction range of IDs currently pinned
Feb 06 20:12:22 16 /mnt/fast/sue/work/mongo/data/db transaction: transaction range of IDs currently pinned
```
At the time of my numbers quoted above, the range was 19, which is reasonable for a test with 20 threads.
@keithbostic had a suggestion for `__wt_update_serial` that I am trying now.

**Comment by sueloverso** [comment]
@michaelcahill This diff solves this problem.
```
--- a/src/include/serial.i
+++ b/src/include/serial.i
@@ -255,8 +255,7 @@ __wt_update_serial(WT_SESSION_IMPL *session, WT_PAGE *page,
         * obsolete check at a time, and to protect updates from disappearing
         * under reconciliation.
         */
-       if (upd->next != NULL &&
-           F_ISSET(S2C(session)->cache, WT_EVICT_ACTIVE)) {
+       if (upd->next != NULL) {
                F_CAS_ATOMIC(page, WT_PAGE_SCANNING, ret);
                /* If we can't lock it, don't scan, that's okay. */
                if (ret != 0)
```
This diff undoes a change that was put a long time ago.  There is no issue listed with it, but it was initially introduced by @keithbostic from @agorrod with this change: eae3d85b10ea.  Then it was changed (on the same day, Oct 16, 2013)  to its current form of a flag by @agorrod here: e371bddf02b567.  The entire code block was recently moved by @michaelcahill last week here: 4b6c1b75d1aa4a.

**Comment by agorrod** [comment]
I see why the above code can be an issue with the huge caches that MongoDB configures. Ideally I think this fix would work similarly to the new code that removes deleted entries from the page.

That is: if we notice an update chain growing large, we mark the page for eviction via the ```__wt_page_evict_soon``` method.

I'm nervous about checking for obsolete updates on every update we add to the page. Since the update check involves switching the page state to scanning, and doing transaction visible checks on all updates in the chain.

We already have a ```__wt_update_list_memsize``` that is called prior to doing the ```__wt_update_serial``` in the row store case. We could change that function from:

```
size_t __wt_update_list_memsize(WT_UPDATE *upd);
```

To:

```
int __wt_update_list_memsize(WT_UPDATE *upd, size_t *size, size_t *count);
```

Then pass in a new flag to ```__wt_update_serial``` that is ```trim_obsolete``` if the update list was long enough. We'd be calling update_list_memsize in the column store case now, but I think that cost is more appealing than the cost of trimming the list every time.

**Comment by michaelcahill** [comment]
That call to `__wt_update_list_memsize` isn't in the common case.  And we only scan for obsolete updates after we check that there is an update after this one in the list.  I'm inclined to take this change and see whether it makes any workloads worse: I'm convinced it will make some better.

**Comment by keithbostic** [comment]
I don't want to evict a page just because it's getting hammered, that's going to spike access to it and there's no need.

I agree we shouldn't check for obsolete updates on every update we add to the page -- but, why not run the list (we don't need a lock to do that), if there are N updates, then check for obsolete updates.

**Comment by michaelcahill** [comment]
We need a lock to walk the list: someone else might be truncating it.

**Comment by agorrod** [comment]
I don't have a better suggestion. Everything I can think of appears about as expensive as just doing the free. Adding tracking for the length of all update chains adds more space and contention. Adding a single count per page has even more contention and is inaccurate.

I vote for trying this out with a variation of the ```bench/wtperf/runners/update-btree.wtperf``` that has a larger cache size and no inserts or reads.

```
conn_config="cache_size=5G"
table_config="type=file"
icount=5000000
report_interval=5
run_time=120
populate_threads=1
threads=((count=2,updates=1))
```

I'll also push the suggested change into a branch, and switch the Jenkins update-btree job to run on it.

**Comment by agorrod** [comment]
The change in #1650 doubles the throughput for the above workload. If I reduce the cache size from 5GB to 500MB (across the 1.3GB of data), then the performance is nearly identical.

**Comment by agorrod** [comment]
I also see matching performance using the wtperf update-btree workload.
