### ISSUE TITLE
Disable recovery from "wt" commands where possible

### ISSUE THREAD

**Issue by michaelcahill** [wiredtiger/wiredtiger#1651]
When running the `wt` command, we should set `log=(enabled=false)` to avoid running recovery, for at least `wt printlog` and `wt verify`.  This would become unnecessary once #736 is implemented.

Should there be a `wt recover` command that just does an ordinary `wiredtiger_open`?

Michael.

**Comment by sueloverso** [comment]
It might be easier to avoid it by default unless it is a command that needs it, or the user wants it.  A `-r` standard option would allow recovery. 

Looking at commands, I think we want no recovery (by default) on any read-only type command:
backup - no
compact - recover
copyright - no
create - recover
drop - recover
dump - no
list - no
load - recover
loadtext - recover
printlog - no
read - no
rename - recover
salvage - recover?
stat - no
upgrade - recover
verify - no
write - recover

**Comment by michaelcahill** [comment]
Thanks, @sueloverso: your list looks good to me.  I think recovery should be off for salvage: it seems dangerous to try if files are corrupted.

**Comment by keithbostic** [comment]
@sueloverso, @michaelcahill: I realize I haven't been part of these discussions to now, but I'd like to understand this better, I would have decided differently.

In the command list, some of these commands can fail in unexpected ways if recovery isn't run. For example, `verify` might fail on a valid object if recovery isn't run, `list` might fail if the metadata file requires recovery, and so on.

The only commands where I'd say recovery shouldn't be run by default are `printlog` and `salvage`, everything else I think might fail if recovery isn't run (where they would have succeeded if recovery were run), and so I think recovery should be the default.

For that reason, I think we should go the other way -- use `-R` as the "don't run recovery" flag and imply recovery for most, if not all, commands.

**Comment by agorrod** [comment]
Could we add an in-memory recovery mode, that applies log updates but never writes to any files on disk? I generally don't expect the utilities to alter the database unless I explicitly ask them to.

**Comment by keithbostic** [comment]
I don't understand why you wouldn't expect the utilities to alter the database?

I just assume `wt load` is going to alter the database, so you're thinking about the utilities differently than I am.

**Comment by sueloverso** [comment]
On the surface, someone who runs the `wt` command but wants to keep their original database completely unchanged is going to need to copy it and run whatever on the copy.  I do agree that having printlog first run recovery and (likely) archive away the log files we wanted to print is less than ideal.  Maybe `wt` should turn off archiving no matter what.

**Comment by agorrod** [comment]
> I just assume wt load is going to alter the database

That is me explicitly asking it to alter the database. On the other hand I don't expect ```wt list``` or ```wt stat``` to change the database. I've lost log files and important context doing that in the past when attempting to investigate crashes.

Not archiving log files would be an OK middle ground, but I'd prefer to think of the commands as read only.

**Comment by sueloverso** [comment]
I think turning archiving off is a different topic, but should be done now.  The question is should the default be on or off, and for what commands.  If we don't run recovery (by default) on some read-only commands, do we run the risk of crashing?  That seems likely.

**Comment by keithbostic** [comment]
I think there's a difference between the behaviors we might want as debuggers, and the possible broader use of the tools by customers.

A customer will be justifiably upset they have to specify a flag to keep `wt stat` from dropping core. Is `wt list` or `wt stat` a customer command?

**Comment by agorrod** [comment]
> keep wt stat from dropping core

I think the commands should work properly. I also think they should not change any files on disk. Maybe I'm increasing the scope of this discussion, if so I'm happy to back off.

If the database had a clean shutdown this should be a moot point - we always write a checkpoint on shutdown.

**Comment by michaelcahill** [comment]
My thinking here is that we should do what we can to keep things simple, while avoiding surprises for users.  How about we make `log.recover` an explicit `wiredtiger_open` config that defaults to `on`, with choices `skip` and `error`?

I suggest we have `wt` set `log.recover=error` by default, for all commands.  That is, if recovery is required because of an unclean shutdown, `wt` will not run it by default, but will instead report `"recovery is required, run wt -r ..."`.  That way, the user is always explicitly aware of running recovery via `wt`, but it doesn't get in the way in the common case where no recovery is required.

**Comment by michaelcahill** [comment]
BTW, to implement this, we need an additional check in the recovery code, when we have figured out the starting point from which to roll forward the log.  If that starting point is not at the end of the log and `recover=error`, we would return a new `WT_RUN_RECOVERY` error.  The `wt` utility would handle this error to generate a meaningful error message.

**Comment by keithbostic** [comment]
I like `log.recover`.

I think `wt` should use the default setting of `on` for two reasons:

First, is there any situation, other than debugging, where a user won't want to run recovery? If not, why require a flag for normally desired behavior? If we wouldn't require a flag to run recovery in WiredTiger, why require a flag for the `wt` utility?

Second, script writers have to remember to set the flag, might not notice if they forgot it, and the script subsequently fails.

So, I would prefer recovery always be run by default, but I can live with this.

**Comment by bdlucas1** [comment]
From a support perspective, I like Michael's suggestion that wt by default
should not modify any db files unless you explicitly ask it to by
specifying the "recover" flag, and error out if recovery is required for
proper operation of the selected command but the "recover" flag is not
specified. On occasion we may need to ask a customer to run a wt command
for diagnostic purposes, and in that case we would certainly not want the
command to modify db files. Customers can be surprisingly effective at
failing to follow instructions, so may easily omit a flag if that is what
is required to prevent wt from modifying their db files. Not modifying db
files by default, and requiring an explicit flag to do recovery, is safer
when in this situation.

**Comment by bdlucas1** [comment]
And to be fair, support personnel can easily forget to tell the customer to
specify a "no recovery" flag, and for that matter debuggers (the people,
not the programs) can easily shoot themselves in the foot by forgetting to
do this as well.

**Comment by sueloverso** [comment]
I'm trying to understand when or why someone would use `recover=skip`?  Having logging enabled, but forcibly skipping recovery seems like it could lead to an unrecoverable state.  A command like `printlog` should disable logging entirely (the reason is that having logging enabled creates a new log file when `wiredtiger_open` is called - so three calls to `wt printlog` would create three new empty log files if logging is enabled regardless of what later happens in recovery).

**Comment by michaelcahill** [comment]
Hi @sueloverso: fair enough, `printlog` was the only use case I could think of, so if it doesn't need `skip`, let's forget about it and make `log.recover` a simple boolean.
