### ISSUE TITLE
read error failed to read bytes

### ISSUE THREAD

**Issue by sueloverso** [wiredtiger/wiredtiger#1708]
In running the insert test to compare current develop with my log-wrlsn-thread branch and running a script to run it in several various settings, I'm seeing a read error about 20% of the time on both branches.  It seems to happen primarily when I have the `wiredTigerConcurrentWriteTransactions` set to 8, 16 or 32.  I have not seen it when it is set to 64 or (the default) 128.  The develop change set is a95b150645ffe and `log-wrlsn-thread` was forked from develop a week ago at changeset b6e6433166d.  So this is not introduced in the last couple of days.

The error is:
```
file:WiredTiger.wt, session.checkpoint: WiredTiger.wt read error: failed to read 4096 bytes at offset 53248: WT_ERROR: non-specific WiredTiger error
```

I'll start investigating the metadata file once my script finishes.

**Comment by sueloverso** [comment]
I managed to get (most of) a stack where this error is occurring.  Also, I added more debug code and the metadata file is exactly 16kb in size, but the offset given is always about 53K.  It is interesting to note that the bad offset given has only been 2 different values in at least a dozen failure logs that I have.  It is always either 53248 (0xd000) or 57344 (0xe000).
```
libwiredtiger-2.5.1.so(__wt_read+0x22A) [0x7f98f0f4bb00]
 libwiredtiger-2.5.1.so(__wt_block_read_off+0x15D) [0x7f98f0eb13b6]
 libwiredtiger-2.5.1.so(__wt_block_extlist_read+0xA6) [0x7f98f0eae021]
 libwiredtiger-2.5.1.so(+0x1D406) [0x7f98f0ea9406]
 libwiredtiger-2.5.1.so(+0x1D6D5) [0x7f98f0ea96d5]
 libwiredtiger-2.5.1.so(__wt_block_checkpoint+0xE0) [0x7f98f0ea92ed]
 libwiredtiger-2.5.1.so(+0x22E9C) [0x7f98f0eaee9c]
 libwiredtiger-2.5.1.so(__wt_bt_write+0x6E5) [0x7f98f0ecb9fc]
 libwiredtiger-2.5.1.so(+0xD7A5A) [0x7f98f0f63a5a]
 libwiredtiger-2.5.1.so(__wt_reconcile+0x4E4) [0x7f98f0f5a965]
 libwiredtiger-2.5.1.so(+0x52E08) [0x7f98f0edee08]
 libwiredtiger-2.5.1.so(__wt_cache_op+0xBD) [0x7f98f0edf118]
 libwiredtiger-2.5.1.so(+0xF9628) [0x7f98f0f85628]
 libwiredtiger-2.5.1.so(__wt_checkpoint+0xAF) [0x7f98f0f858d4]
 libwiredtiger-2.5.1.so(__wt_txn_checkpoint+0xAC7) [0x7f98f0f84513]
 libwiredtiger-2.5.1.so(+0xEB640) [0x7f98f0f77640]
 libwiredtiger-2.5.1.so(+0x6CD79) [0x7f98f0ef8d79]
```

**Comment by sueloverso** [comment]
Turning on `VERB_READ` shows this line in `__wt_block_read_off`:
```
[1424986773:979788][378:0x7fbc1dfd1700], file:WiredTiger.wt, session.checkpoint: off 53248, size 4096, cksum 3747670907
```
No surprise there as that is the offset we see.  @keithbostic what information should I gather, and from where to push this issue past triage?  Or if you want to send me a diff or a debug branch, I can run it against that.

Another anomaly I noticed is that, with my script, it *always* happens on every other run when using 8, 16 and 32 threads.  I have no idea why or how that might be significant.

**Comment by keithbostic** [comment]
@sueloverso, I'm happy to take a run at this one -- can we connect tomorrow and you show me how to run the test?

**Comment by sueloverso** [comment]
@keithbostic Sure.  I am out from 9am until early afternoon, so I'll email you the scripts and steps to repro now.  Then we'll connect when I'm back.

**Comment by keithbostic** [comment]
@sueloverso, I think this is a bug in the `runinsert.sh` script. The line
```
kill `cat $pidfile`
``` 
sends SIGTERM to mongod, which catches the signal and does an orderly shutdown. My guess is mongod doesn't shut down fast enough, so:
- we start a second mongod while the old mongod is still running,
- the old mongod writes a `WiredTiger.turtle` file the new mongod reads,
- and the stored checksum offset doesn't exist in the underlying file.

I didn't actually prove the turtle file was racing, but if I make this change:
```
< 		kill `cat $pidfile`
< 		if test "$?" -ne "0"; then
< 			echo "FAIL:  EXIT"
< 			exit 1
< 			cp $DBDIR/MDB.log /tmp/MDB.logfail.$icount.$t
< 		fi
---
> 		killall -9 mongod
```
the script runs for me (and this neatly explains why every other run fails), so I declared victory and quit digging.

Let me know if that change doesn't fix the problem for you and I'm happy to chase further.

**Comment by michaelcahill** [comment]
Why doesn't `WiredTiger.lock` protect against this?

**Comment by sueloverso** [comment]
Thanks for chasing that user error, Keith.  That makes sense.

**Comment by michaelcahill** [comment]
I should add that I don't have the script: is it removing the database manually in between?

Maybe we should have a "wt destroy ..." or "wt newdb ..." command that does this safely for scripts?

**Comment by sueloverso** [comment]
Yes, it is starting mongod each time, and doing an rm -rf on the DBDIR in between.
