### ISSUE TITLE
Connection reconfigure can over-subscribe shared cache

### ISSUE THREAD

**Issue by agorrod** [wiredtiger/wiredtiger#1712]
The current implementation of ```WT_CONNECTION::reconfigure``` when a shared cache is being used can lead to invalid reserved settings and mis-calculation as to whether the new allocation would over-subscribe the shared cache.

**Comment by agorrod** [comment]
The current logic for cache and shared cache configuration is confusing. The order of creation/configuration leads to needing to be very careful about when fields/values are updated.

The logic deserves to be split out and simplified. I plan to add a new ```__wt_cache_config``` method, that will control the order of operations, so the logic is all centralized.

**Comment by agorrod** [comment]
@keithbostic Could you take a look at this change please? The issue before boiled down to us called ```cache_config``` and ```cache_pool_config``` in different orders when called from create versus reconfigure.

I've straightened out that, and simplified some other code. We used to jump through hoops to avoid creating a WT_CACHE structure when using a shared cache, but we haven't done that for a long time now - which is why these changes are possible.

**Comment by keithbostic** [comment]
@agorrod, I made a few trivial changes, but lgtm, I'll merge.
