### ISSUE TITLE
support floating point formats

### ISSUE THREAD

**Issue by dmitri-shubin** [wiredtiger/wiredtiger#1724]
Hi!

Are there any plans to support floating-point formats in scheme?
Python struct has 'f' and 'd'.
Currently I can probably use integer types of the same size (I don't need to use them as keys, so ordering isn't important).

Thank!

**Comment by ddanderson** [comment]
Hi @dmitri-shubin, there are no plans to add floating point numbers in the schema. Supporting this probably requires us to have a representation that ordered "correctly" and imposing ordering for artifacts of IEEE floats like NaN and -0 vs +0. For your use case, you should cast to the appropriate sized integer.
