### ISSUE TITLE
test/format recovery test failed

### ISSUE THREAD

**Issue by sueloverso** [wiredtiger/wiredtiger#1726]
http://build.wiredtiger.com:8080/job/wiredtiger-test-format-recovery/209/

The console output is:
```
[1425592011:378909][50238:0x7f91572e8780], t, file:wt.wt, session.verify: read checksum error [1024B @ 25327104, 1733899928 != 3541655368]
[1425592011:387446][50238:0x7f91572e8780], t, file:wt.wt, session.verify: checkpoint ranges never verified: 2011
[1425592011:391167][50238:0x7f91572e8780], t, file:wt.wt, session.verify: file ranges never verified: 214
```
The CONFIG is:
```
############################################
#  RUN PARAMETERS
############################################
abort=1
auto_throttle=1
firstfit=0
bitcnt=7
bloom=1
bloom_bit_count=52
bloom_hash_count=7
bloom_oldest=0
cache=82
checkpoints=1
checksum=uncompressed
chunk_size=8
compaction=0
compression=bzip
data_extend=1
data_source=table
delete_pct=12
dictionary=0
evict_max=2
file_type=row-store
backups=0
huffman_key=0
huffman_value=0
insert_pct=6
internal_key_truncation=1
internal_page_max=11
isolation=random
key_gap=4
key_max=46
key_min=15
leak_memory=0
leaf_page_max=13
logging=0
logging_archive=0
logging_prealloc=0
logging=0
lsm_worker_threads=3
merge_max=20
mmap=1
ops=109596
prefix_compression=1
prefix_compression_min=8
repeat_data_pct=0
reverse=0
rows=155855
runs=0
split_pct=43
statistics=0
statistics_server=0
threads=30
timer=2
value_max=2415
value_min=6
wiredtiger_config=
write_pct=41
############################################
```
I copied and unpacked the tar file in ~jenkins/recovery.209 on tinderbox.

**Comment by sueloverso** [comment]
There may be a couple things going on here.  First, somehow `logging` got turned off in the CONFIG, as shown above, even though the script explicitly sends in this:
```
$tcmd $config -q abort=1 logging=1 timer=$timer
```
The `abort` and `timer` settings are correct but logging is not.  That seems like a bug in test/format in generating its final CONFIG in some way (I haven't yet pursued this).

The second thing is whether the error is legitimate given the random abort and the fact that we're not logging.  The data on disk results in the error shown when `verify` is run.  If I run `salvage` on `table:wt` it then verifies successfully after.

**Comment by agorrod** [comment]
@sueloverso This came up again in test-format-recovery. I agree with your analysis re: logging not being turned on - I pushed a fix (see above commit) to test format.
