### ISSUE TITLE
Need way to ignore basecfg or turn off logging for wt command

### ISSUE THREAD

**Issue by sueloverso** [wiredtiger/wiredtiger#1732]
Several times this week developers have wanted to run the `wt` command on a copy of a database directory.  They know it is a good copy and they don't copy nor want to copy all the log files in the journal directory.  Running `wt` runs recovery for all but the printlog command and creates new log files, etc.  It would be good to have an arg, perhaps undocumented, that either tells it to ignore basecfg, or at least just forces logging off.  The recent `-R` command was added to force recovery to run.  We have the infrastructure now for turning it off, but not the mechanism for debugging and diagnostic purposes.

**Comment by michaelcahill** [comment]
It would be handy to have an option to `wt` to disable logging -- that seems better to me than completely ignoring the `basecfg` file.
