### ISSUE TITLE
wtstats innacurate

### ISSUE THREAD

**Issue by agorrod** [wiredtiger/wiredtiger#1742]
I was looking at some statistics via the wtstats graph tool, and they don't appear to match those in the original file.

The two statistics are:

```
tracked dirty bytes in the cache
```
and
```
bytes currently in the cache
```

The wtstats graph I see for those two statistics is:

![screen shot 2015-03-10 at 5 48 52 pm](https://cloud.githubusercontent.com/assets/1930121/6570405/ffdab416-c74d-11e4-941f-429fccdbfcd3.png)

An extract of the raw data is:

```
Mar 10 06:00:07 13937645434 /mnt/fast/alexg/data cache: tracked dirty bytes in the cache
Mar 10 06:00:07 15032413045 /mnt/fast/alexg/data cache: bytes currently in the cache
--
Mar 10 06:00:17 14118949794 /mnt/fast/alexg/data cache: tracked dirty bytes in the cache
Mar 10 06:00:17 15031434886 /mnt/fast/alexg/data cache: bytes currently in the cache
--
Mar 10 06:00:27 14245210823 /mnt/fast/alexg/data cache: tracked dirty bytes in the cache
Mar 10 06:00:27 15032327122 /mnt/fast/alexg/data cache: bytes currently in the cache
--
Mar 10 06:00:37 13829546010 /mnt/fast/alexg/data cache: tracked dirty bytes in the cache
Mar 10 06:00:37 14839582962 /mnt/fast/alexg/data cache: bytes currently in the cache
--
Mar 10 06:00:47 13598968927 /mnt/fast/alexg/data cache: tracked dirty bytes in the cache
Mar 10 06:00:47 15030610981 /mnt/fast/alexg/data cache: bytes currently in the cache
--
Mar 10 06:00:57 13407003442 /mnt/fast/alexg/data cache: tracked dirty bytes in the cache
Mar 10 06:00:57 15032283870 /mnt/fast/alexg/data cache: bytes currently in the cache
--
Mar 10 06:01:07 14325052454 /mnt/fast/alexg/data cache: tracked dirty bytes in the cache
Mar 10 06:01:07 15031068774 /mnt/fast/alexg/data cache: bytes currently in the cache
--
Mar 10 06:01:17 14373973388 /mnt/fast/alexg/data cache: tracked dirty bytes in the cache
Mar 10 06:01:17 15031787034 /mnt/fast/alexg/data cache: bytes currently in the cache
--
Mar 10 06:01:27 14959868383 /mnt/fast/alexg/data cache: tracked dirty bytes in the cache
Mar 10 06:01:27 15032397299 /mnt/fast/alexg/data cache: bytes currently in the cache
--
Mar 10 06:01:37 14865619787 /mnt/fast/alexg/data cache: tracked dirty bytes in the cache
Mar 10 06:01:37 15032398484 /mnt/fast/alexg/data cache: bytes currently in the cache
```

I wonder whether the tool is treating the tracked dirty bytes as a running total rather than an absolute number?

**Comment by rueckstiess** [comment]
I think this is because "bytes currently in the cache" is in the `no_clear_list`, but "tracked dirty bytes in the cache is not. See [here](https://github.com/wiredtiger/wiredtiger/blob/develop/tools/wtstats/stat_data.py#L58). 

If a stat is **not** on this list, wtstats.py will compute the difference to the last value and plot that ([code](https://github.com/wiredtiger/wiredtiger/blob/develop/tools/wtstats/wtstats.py#L71-88)).

There is also a `--clear` option to influence the behavior of wtstats.py. If this option is set, all values are treated as absolute and no difference is computed.

The question is: should the "bytes currently in the cache" stat also be added to that list? Are there others that need to be added?

**Comment by agorrod** [comment]
Thanks @rueckstiess I've pushed a fix for the dirty bytes change and one other.

@keithbostic Could you do a pass over the flags for statistics values as well? If you are happy please close the issue.

**Comment by agorrod** [comment]
@keithbostic Would you mind doing a pass over stat_data.py and checking to see whether all the flags values make sense to you in light of this issue?

**Comment by keithbostic** [comment]
@agorrod, I did a pass and made some changes -- can you please review 4790f13, and then I think #1742 is ready to close.

**Comment by agorrod** [comment]
Thanks @rueckstiess lgtm. This issue is done for now.
