### ISSUE TITLE
Extract Data From a WiredTiger Collection FIle

### ISSUE THREAD

**Issue by Gentlehag** [wiredtiger/wiredtiger#1743]
Hi

I've a corrupted MongoDb with WiredTiger Engine database.

i urgently need data from a single collection file. is there a way to extract the data of a single wired tiger collection file ?

**Comment by keithbostic** [comment]
@gentlehag: can we move this to [SUPPORT-1254?](https://jira.mongodb.org/browse/SUPPORT-1254)
