### ISSUE TITLE
LZ4 supports stream compression

### ISSUE THREAD

**Issue by keithbostic** [wiredtiger/wiredtiger#1773]
LZ4 supports stream compression as well as block compression, we should take advantage of that in WiredTiger in the same way we use stream compression in zlib.

**Comment by michaelcahill** [comment]
LZ4 streaming works in 64KB chunks, as I understand it -- the design is for compressing large files without needing to load all of the file into memory at once.  When I looked last year, it wasn't clear that it would be useful in raw compression, which works at the granularity of records.

**Comment by keithbostic** [comment]
I asked: We're currently using the LZ4 block APIs: we format a set of table rows in a block of memory, compress that block, and then write the result to stable storage. However, that's not optimal for applications focused on the size of their underlying SSD objects, because we cannot control the final write size, the resulting size is whatever it is.

With zlib, we can incrementally append table rows to the compressed image until we reach a result as close as possible to the target result size.

Would it be reasonable to use the LZ4 streaming APIs in that way, that is, feeding relatively small chunks of data to the LZ4_compress_continue API until the target size is reached?

> The reply: The answer is yes, it will work as you suggest.

> Looking into details, keep in mind the following limitations:

> Relatively small should nonetheless remain "large enough". There are some inefficiencies to recoup after each call. Your mileage will vary of course depending on data to compress, so you'll have to test to select your lowest threshold. For example, I've received good results from people attempting to add small chunks as low as 64 bytes, but in general, I would recommend to define a "small chunk" as something no lower than ~200 bytes.

> LZ4_compress_continue() doesn't save any header information. You'll have to handle them on your own (typically, size of compressed chunks). If you're looking for an API which automatically handles headers too, look for lz4frame instead. But the additionnal headers will cost some more bytes.

**Comment by daveh86** [comment]
I had a look at implementing this and hit a number of walls.

If we were to use the streaming API we would need to track the exact size of the output each time we call the compress_continue function, this would add a considerable amount of overhead if we are looking to compress a number of small values into a larger block.

I also looked at using the LZ4 Frame API. This is built along the lines of what we have in mind, but allows only 4 fixed sizes for blocks, 64K, 256K, 1M and 4M. It looks like it is possible to create smaller pages, by under-filling them, but if we allocate less space than the block size (less than 64K by default) LZ4 will error. There is also no easy means of estimating what the compressed size of each input would be so we would need to take the "change then maybe rollback" approach.
