### ISSUE TITLE
wiredtiger-configure-combinations failure

### ISSUE THREAD

**Issue by sueloverso** [wiredtiger/wiredtiger#1778]
This Jenkins test has been failing for a few days.  @agorrod or @keithbostic  can you take a first look?  They all are failing with the same thing.  Here's one example

http://build.wiredtiger.com:8080/job/wiredtiger-configure-combinations/640/

The error in the console log is:
```
checking if --with-builtins option specified... configure: error: Unknown builtin extension "bz2"
+ return 1
+ ecode=1
```

**Comment by agorrod** [comment]
Hi,

That is my fault. I changed the Jenkins job yesterday to test the new lz4
support. I guess I got a bit over zealous. I'll fix it today.

Alex
