### ISSUE TITLE
Switch __wt_thread_create to use beginthread on Windows

### ISSUE THREAD

**Issue by michaelcahill** [wiredtiger/wiredtiger#1791]
Feedback from Laurent Dupuis on http://groups.google.com/group/wiredtiger-users:

> A thread in an executable that calls the C run-time library (CRT) should use the _beginthreadex and_endthreadex functions for thread management rather than CreateThread and ExitThread; this requires the use of the multithreaded version of the CRT. If a thread created using CreateThread calls the CRT, the CRT may terminate the process in low-memory conditions.

**Comment by keithbostic** [comment]
Closed by @markbenvenuto with the merge of #1821.
