### ISSUE TITLE
WT encryption modifications needed

### ISSUE THREAD

**Issue by ddanderson** [wiredtiger/wiredtiger#1822]
This issue discusses encryption design and implementation.

**Comment by sueloverso** [comment]
(There is no way I see to assign multiple people to an issue.)  I'll get a branch created that we can use for this work and push it.

**Comment by ddanderson** [comment]
What would a WT encryption callback look like?  @sueloverso and I have been discussing this:

This feels very similar to compression.  We'll need to encrypt/decrypt in
the logging and block managers.  We'll clearly need a flag to indicate
crypto in the headers as well.  There is space in both page and log record
headers for the flag.  The typical use case will have both compression and
encryption, but we should allow any combination, with the ability to mix any
configured compression algorithm with any configured encryption algorithm.

If doing both then the order on the way out to disk would be compress,
encrypt, write.  On the way in, read, decrypt, uncompress.

Differences in the API from compression:
- No need for a 'raw' callback - that seems to address a specific customer need.
- The addition of a 'post_size'.  Whereas 'pre_size' gives the size needed for the output buffer when encrypting, 'post_size' takes as input the encrypted buffer and returns a size that is sufficient
  to store the unencrypted buffer.  It is optional, and when not present,
 
@sueloverso writes:
Memory management: When I did BDB crypto, it needed to store an initialization vector in the header of the encrypted data.  That was 16 bytes long.  If we're handing this to a callback, we don't know for sure what they need.  We're going to have to do some kind of configuration setting to allocate any additional space needed for records.  Everything in memory will be in the clear.

Setup and configuration:  I think it may be minimal.  We don't need to store the passwd, as that is the responsibility of the callback layer.  While crypto may be set on session->create and some tables are encrypted and others may not be, encrypting the logs is going to be a database-wide setting no matter what.  I don't think we should have log records mixed in a log.  Although I suppose we could have, as the code is structured in a way that it should happen automatically.

**Comment by ddanderson** [comment]
We'll want some way to prevent an unencrypted log file from being used when a file has a block compressor configured. (Otherwise, the caller may believe that they've encrypted, when they're leaving data in the clear). We've talked about some mechanisms to do this.

**Comment by ddanderson** [comment]
Another goal is to allow different keys per table. For arguments sake, start with a simple minded translation of the compressor interface to become the new encryptor interface.  We could only have separate keys/table by configuring a different encryptor struct per table, and doing a separate add_encryptor call for each table, with a unique identifying name.  Doing this, we could store any key information in the interface struct. It's ugly, and not sure if this scales, the current design was not thinking of having a huge number of plugins. Another approach is to have some per-table (or log) information that is available to the `encrypt()` or `decrypt()` calls - essentially some state information that can be created on the `session.create()` call (or `wiredtiger_open` for logging) and referred to during the callbacks.  Using that model, we may need a separate terminate callback to allow the compressor to dispose of it.

**Comment by sueloverso** [comment]
@ddanderson I have pushed an initial branch `encryption-api`.  It just has some plumbing added and some config items.  I copied the compressor functions and changed the names, but did not modify any args.  Mostly it was a lot of replacing 'compress' with 'encrypt'.  This does build, but does nothing real, but can get us on our way.

**Comment by ddanderson** [comment]
Blocks may have checksums.  We'll want to make sure the checksum (if present) is performed on the encrypted text so as to not leak information about the plaintext.  I'm pretty sure compressed buffers are not this way (checksum is on the plaintext).

**Comment by sueloverso** [comment]
Looks like there may be lots of checksums all around.  Each layer may do its own checksums.  I certainly would expect an encryption implementation to add its own.  Taking a log record for example, it may be compressed and the new record buffer would contain a checksum.  Then it may be encrypted and that new buffer would contain a checksum.  Then the logging subsystem fills in all of its information and performs a checksum on the real record written.

For encryption callbacks, I agree they should checksum the encrypted data.  However from our perspective, they just give us an opaque buffer back.

**Comment by ddanderson** [comment]
@sueloverso, I made mods to the pull request to fix some things in the example, config and plumbing.  The encryptor is now called in the example, should be mostly working, but I haven't verified on disk yet.  There are references in code to `WT_LOG_COMPRESS_SKIP`, this define is now poorly named, it's the size of the untouched header (which is the same for compression and encryption).
