### ISSUE TITLE
log compression doesn't work with log cursors

### ISSUE THREAD

**Issue by sueloverso** [wiredtiger/wiredtiger#1837]
I discovered a bug today that log cursors don't work when log compression is being used.  This does not affect printlog nor recovery as those walk the log with `__wt_log_scan` and they do not use cursors although it does affect the `__wt_log_needs_recovery` function.  @ddanderson has written a unit test to combine log cursors and compression testing.

**Comment by michaelcahill** [comment]
What is the effect on `__wt_log_needs_recovery`?  Are we going to run recovery when it isn't required (extra work), or skip recovery when it is required (potential data loss)?

**Comment by sueloverso** [comment]
It might run recovery when it isn't required.  Basically, the next() call may not detect it could skip recovery.
