### ISSUE TITLE
Don't close handles until a threshold of in-use handles has been reached

### ISSUE THREAD

**Issue by agorrod** [wiredtiger/wiredtiger#1856]
At the moment WiredTiger has a sweep server that automatically closes file handles if they have been idle for over 30 seconds. Idle means that there are no cursors open on the file.

That can lead to undesirable behavior - we may flush a file from cache, even when the cache isn't full.

It makes sense to only consider closing handles once we are using a certain number of file handles. A reasonable start might be 200 file handles.

This is related to MongoDB [SERVER-17907](https://jira.mongodb.org/browse/SERVER-17907)

**Comment by monkey101** [comment]
This issue is reflected in mongodb jira as https://jira.mongodb.org/browse/SERVER-17514

**Comment by keithbostic** [comment]
Closed with the merge of #1858, note in SERVER-17514.
