### ISSUE TITLE
Reduce allocation overhead in cache when idle

### ISSUE THREAD

**Issue by agorrod** [wiredtiger/wiredtiger#1857]
There are cases where WiredTiger will maintain many pages in cache for a clean tree. Those pages may contain empty update and modify structures.

It would be good if we could have a "maintenance" mode for eviction (or possibly the sweep server) that looks for such pages, even when the cache isn't full, and rewrites the in-memory version to be clean.

The motivation for the change is that there is overhead in memory allocators. WiredTiger tends to allocate many small chunks of memory. With a large cache (10s of GB), the time to free those structures (even if there is nothing to reconcile) can be high.

Related to MongoDB JIRA issue [SERVER-17907](https://jira.mongodb.org/browse/SERVER-17907)

**Comment by agorrod** [comment]
@keithbostic I've attempted to capture what we talked about this morning, re: cleaning the cache to make it faster to close files. I don't feel like I've done a great job. I'd appreciate if you can add your 2c here.

**Comment by bdlucas1** [comment]
Is there a way I can tell - via wt counters for example - whether this is
the case in a particular instance? (Either per-tree or global information
would be useful.)

**Comment by keithbostic** [comment]
No, I can't think of any way to identify a page with a lot of small allocations vs. a page with a few large allocations, further, it can change as the transaction state of the system changes (for example, we can discard MVCC allocations as they're no longer needed).
