### ISSUE TITLE
cache: maximum page size at eviction exceeds memory_page_max by a large factor

### ISSUE THREAD

**Issue by daveh86** [wiredtiger/wiredtiger#1869]
Running wtperf with the following configuration will generate maximum page sizes that are aprx 7x larger than the given memory_page_max size.

    conn_config="cache_size=100MB,statistics=(all),statistics_log=(wait=10)"
    database_count=1
    table_config="leaf_page_max=4k,internal_page_max=16k,leaf_item_max=1433,internal_item_max=3100,type=file,memory_page_max=10m,split_pct=90,leaf_value_max=1MB"
    icount=50000000
    populate_threads=10
    random_range=10000000
    report_interval=5
    run_time=0
    threads=((count=1,reads=1),(count=1,inserts=1))
    value_sz=100
    warmup=10

This run takes 30~ seconds to form the first very large page when running on my OSX Macbook Pro

Relates to MongoDB ticket SERVER-16902

**Comment by michaelcahill** [comment]
@daveh86, does the 7x figure scale?  That is, if you change the config to `memory_page_max=20MB`, does the largest page size grow to 140MB?

Also, how does this vary if the number of threads is increased?
