### ISSUE TITLE
Java binding doesn't allow backup cursors

### ISSUE THREAD

**Issue by grogers0** [wiredtiger/wiredtiger#2017]
The java cursor implementation for next() always calls get_value_wrap() if the underlying cursor next() returns successfully. The get_value_wrap() function throws an exception if the underlying cursor get_value() returns non-zero. Backup cursors only yield values, not keys: the get_value() function returns ENOTSUP, and thus will always throw an exception when you call the java next().

Probably the easiest way to fix it is to check if the value format is empty, and if so don't try to retrieve a value.

**Comment by ddanderson** [comment]
@grogers0, WiredTiger has transitioned to MongoDB's JIRA server. Since this is a WT implementation issue, please open a ticket at https://jira.mongodb.org/browse/WT .  Thanks!
