### ISSUE TITLE
Java build fails

### ISSUE THREAD

**Issue by krisskross** [wiredtiger/wiredtiger#2052]
Hi

The Java build of 2.6.1 fails with the following error on Debian Jessie.

Making all in lang/java
make[2]: Entering directory '/home/stoffe/dev/wiredtiger/lang/java'
(cd . && \n     -Wall -v -java -nodefaultctor -nodefaultdtor -package com.wiredtiger.db -I/home/stoffe/dev/wiredtiger -outdir src/com/wiredtiger/db -o wiredtiger_wrap.c wiredtiger.i)
/bin/bash: line 1: -Wall: command not found
Makefile:1170: recipe for target 'wiredtiger_wrap.c' failed
make[2]: *** [wiredtiger_wrap.c] Error 127
make[2]: Leaving directory '/home/stoffe/dev/wiredtiger/lang/java'
Makefile:1973: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/stoffe/dev/wiredtiger'
Makefile:906: recipe for target 'all' failed
make: *** [all] Error 2

Cheers,
-Kristoffer

**Comment by michaelcahill** [comment]
Can you please include your full `configure` command line and output?  It looks like `javac` is not being found...

**Comment by krisskross** [comment]
$ ./configure --enable-java
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking if --enable-attach option specified... no
checking if --with-builtins option specified... 
checking if --enable-bzip2 option specified... no
checking if --enable-diagnostic option specified... no
checking if --enable-java option specified... yes
checking if --enable-leveldb option specified... no
checking if --enable-python option specified... no
checking if --with-python-prefix option specified... 
checking if --enable-snappy option specified... no
checking if --enable-lz4 option specified... no
checking if --enable-tcmalloc option specified... no
checking if --with-spinlock option specified... pthread
checking if --enable-verbose option specified... no
checking if --enable-zlib option specified... no
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s

checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for swig2.0... no
checking for swig... no
configure: WARNING: SWIG is required to rebuild Java or Python APIs.
checking if javac works... yes
checking for jar... jar
checking /home/stoffe/Downloads/jdk1.8.0_31/include/jni.h usability... yes
checking /home/stoffe/Downloads/jdk1.8.0_31/include/jni.h presence... yes
checking for /home/stoffe/Downloads/jdk1.8.0_31/include/jni.h... yes
checking for kaffe... no
checking for java... java
checking for uudecode... no
configure: WARNING: I have to compile Test.class from scratch
checking if java works... yes
checking for org.junit.runner.JUnitCore class... no
checking for junit... 
checking for FILE *... yes
checking for pid_t... yes
checking for size_t... yes
checking for ssize_t... yes
checking for time_t... yes
checking for off_t... yes
checking for uintmax_t... yes
checking for uintptr_t... yes
checking x86intrin.h usability... yes
checking x86intrin.h presence... yes
checking for x86intrin.h... yes
checking for pthread_create in -lpthread... yes
checking for dlopen in -ldl... yes
checking for sched_yield in -lrt... yes
checking for clock_gettime... yes
checking for fallocate... yes
checking for fcntl... yes
checking for fread_unlocked... yes
checking for ftruncate... yes
checking for gettimeofday... yes
checking for posix_fadvise... yes
checking for posix_fallocate... yes
checking for posix_madvise... yes
checking for strtouq... yes
checking for sync_file_range... yes
checking for fdatasync... yes
checking for working posix_memalign... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking whether byte ordering is bigendian... no
checking if --with-berkeleydb=DIR option specified... NO_BERKELEY_DB_LIBRARY
checking if --with-helium=DIR option specified... NO_HELIUM_LIBRARY
checking for doxygen... false
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating ext/collators/reverse/Makefile
config.status: creating ext/compressors/bzip2/Makefile
config.status: creating ext/compressors/lz4/Makefile
config.status: creating ext/compressors/nop/Makefile
config.status: creating ext/compressors/snappy/Makefile
config.status: creating ext/compressors/zlib/Makefile
config.status: creating ext/datasources/helium/Makefile
config.status: creating ext/encryptors/nop/Makefile
config.status: creating ext/encryptors/rotn/Makefile
config.status: creating ext/extractors/csv/Makefile
config.status: creating ext/test/kvs_bdb/Makefile
config.status: creating api/leveldb/Makefile
config.status: creating bench/wtperf/Makefile
config.status: creating examples/c/Makefile
config.status: creating lang/java/Makefile
config.status: creating examples/java/Makefile
config.status: creating lang/python/Makefile
config.status: creating test/bloom/Makefile
config.status: creating test/checkpoint/Makefile
config.status: creating test/fops/Makefile
config.status: creating test/format/Makefile
config.status: creating test/huge/Makefile
config.status: creating test/packing/Makefile
config.status: creating test/salvage/Makefile
config.status: creating test/thread/Makefile
config.status: creating Makefile
config.status: creating wiredtiger.h
config.status: creating wiredtiger.pc
config.status: creating wiredtiger_config.h
config.status: wiredtiger_config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

**Comment by krisskross** [comment]
If is there's a prebuilt jar available somewhere i'm happy to use it.

**Comment by agorrod** [comment]
@krisskross We have moved to JIRA from the GitHub issue tracking system. I have moved this ticket to our JIRA bug tracker here:
https://jira.mongodb.org/browse/WT-2003

Please check there for further updates.
