### ISSUE TITLE
pg_row_entries macro is repeated?

### ISSUE THREAD

**Issue by yuanrongxi** [wiredtiger/wiredtiger#2379]
I find that pg_row_entries macro is repeated, in btmem.h line 470:
#define	pg_row_entries	u.row.entries
#define	pg_row_entries	u.row.entries
it should be
#undef     pg_row_entries
#define	pg_row_entries	u.row.entries
Is that right?

**Comment by agorrod** [comment]
Thanks for the report - and I believe you are correct. I have moved the content to JIRA, since we are no longer using GitHub for issue tracking. You can follow it's progress here:
https://jira.mongodb.org/browse/WT-2284
