### ISSUE TITLE
Make a release for mongodb 3.2.2?

### ISSUE THREAD

**Issue by felixonmars** [wiredtiger/wiredtiger#2499]
The test suite of mongodb 3.2.2 no longer passes with the latest wiredtiger 2.7.0 release due to missing "lock_wait" argument. Would it be possible to release a new patch version for this?

**Comment by agorrod** [comment]
@felixonmars we are no longer using GitHub to track WiredTiger issues. Please open a ticket in the WT Jira project (https://jira.mongodb.org/browse/WT) instead.
