### ISSUE TITLE
checkpoint_sync=false does *not* prevent flushes/sync to disk.

### ISSUE THREAD

**Issue by stephan-hof** [wiredtiger/wiredtiger#2557]
Hi,

I'm opening wiredtiger with the described setting above. I'm aware of the consequences: In a power-off scenario my database is corrupted or not usable anymore, but in my case this is acceptable (strong replication).

Still I can see on each checkpoint interval (60 seconds):
- heavy disk usage
- decreased throughput in my application

I looked a bit through the wiredtiger code and found out that this line of code is the culprit:
https://github.com/wiredtiger/wiredtiger/blob/2.7.0/src/btree/bt_sync.c#L253 

I would consider this as a bug, this setting says "Please do not sync", but still the code does.

Another thing, the comment there says 
> Start a flush to stable storage, but don't wait for it

Which is not entirely true. If you look at the [man-age](http://man7.org/linux/man-pages/man2/sync_file_range.2.html) it says that the call can block if there is already much disk IO happening.

**Comment by sueloverso** [comment]
Hello.  We have migrated from github issues to JIRA tickets.  I have created a WiredTiger JIRA ticket.  You can find it at https://jira.mongodb.org/browse/WT-2454

**Comment by keithbostic** [comment]
@stephan-hof, thanks for the bug report, I've opened a branch in #2560 to fix the problem.

With respect to `Start a flush to stable storage, but don't wait for it`, yes, I agree, that can stall, but it makes a big difference in some workloads to get I/O started, and I don't have a better solution. If you have any ideas as to how we could improve our approach, please let me know.

**Comment by stephan-hof** [comment]
Many thanks for the quick response to address the problem.

Regarding 
> Start a flush to stable storage, but don't wait for it

I agree, at the moment the linux kernel provides no better way (up to me knowledge) to trigger an async flush. In general I don't see  a problem.

I mentioned it, because you (wiredTiger development) can better judge if blocking behaviour in this specific part of the code does harm or not. A stupid example could be:
```
acquire_spinlock()
...other code.....
sync_file_range
.....other code ...
release_spinlock()
```
As soon as one thread is in the critical section, other thread(s) are hammering on the spinlock until the sync_file_range happened.
I know the example is not sophisticated, it should just illustrate what I had in mind.
