### ISSUE TITLE
docs confusing for parallel readonly

### ISSUE THREAD

**Issue by abe-winter** [wiredtiger/wiredtiger#2909]
Parallel readonly only works when the filesystem permissions on the wiredtiger home directory are non-writable. Can you edit your docs to say this explicitly?

http://source.wiredtiger.com/2.8.0/readonly.html

**Comment by agorrod** [comment]
Hi,

Thanks for the report. We have switched our bug tracker to JIRA. I have opened a ticket there instead:
https://jira.mongodb.org/browse/WT-2795

In the future please use JIRA to open new tickets.
