### ISSUE TITLE
lsm merge span issue

### ISSUE THREAD

**Issue by squalfof** [wiredtiger/wiredtiger#3546]
Within __lsm_merge_span()

1.  https://github.com/wiredtiger/wiredtiger/blob/master/src/lsm/lsm_merge.c#L324
- Once `end_chunk` is updated, shouldn't `chunk_size` be reset to 0 as `record_count` does ?
```
if (end_chunk > lsm_tree->merge_min && 
    oldest_gen - youngest_gen > max_gap) {
	--end_chunk;
	goto retry_find;
}
```

2. https://github.com/wiredtiger/wiredtiger/blob/master/src/lsm/lsm_merge.c#L287
- Is it possible that "chunk_of_youngest != end_chunk" ?
```
F_CLR(youngest, WT_LSM_CHUNK_MERGING);
record_count -= youngest->count;
chunk_size -= youngest->size;
--end_chunk;
```

**Comment by michaelcahill** [comment]
We are not using GitHub to track WiredTiger issues.  If you think this is a bug, please open a jira ticket: https://jira.mongodb.org/browse/WT
