### ISSUE TITLE
how to reconfig  statistics log dir of wiredTiger via db.command

### ISSUE THREAD

**Issue by Shawn001** [wiredtiger/wiredtiger#3547]
hi:

as mentions in this url:    https://jira.mongodb.org/browse/WT-2711

No longer support setting the statistics_log path in WT_CONNECTION::reconfigure.
No longer support setting a custom name for statistics files, only allow a destination directory.

I want to change  statistics  log dir to another dir , execute command like this:

> db.adminCommand({setParameter: 1, wiredTigerEngineRuntimeConfig: "log=(path=/log/slog/)"})
{
        "was" : "",
        "code" : 2,
        "ok" : 0,
        "errmsg" : "WiredTiger reconfiguration failed with error code (22): Invalid argument"
}

return errors,

how should i do  to change this dir, my  WT version is ：
WiredTiger
WiredTiger 2.9.2: (December 23, 2016)

Thanks.

**Comment by michaelcahill** [comment]
We are not using GitHub to track issues with WiredTiger or MongoDB.  Since this is a question about MongoDB, please ask on https://groups.google.com/forum/#!forum/mongodb-user
